=== yulinliu/JQuickMacro/script/JQuickMacro.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT ExitTime ( #PCDATA ) >

<!ELEMENT ScreenCapture ( #PCDATA ) >
<!ATTLIST ScreenCapture height CDATA #REQUIRED >
<!ATTLIST ScreenCapture width CDATA #REQUIRED >
<!ATTLIST ScreenCapture x CDATA #REQUIRED >
<!ATTLIST ScreenCapture y CDATA #REQUIRED >

<!ELEMENT Thread ( event+ ) >
<!ATTLIST Thread autodelay CDATA #REQUIRED >
<!ATTLIST Thread name CDATA #REQUIRED >
<!ATTLIST Thread repeatedly CDATA #REQUIRED >

<!ELEMENT Threads ( singleCheck, Thread+, ExitTime ) >
<!ATTLIST Threads eventDelay CDATA #REQUIRED >
<!ATTLIST Threads singleWindow CDATA #REQUIRED >
<!ATTLIST Threads startWait CDATA #REQUIRED >

<!ELEMENT event ( #PCDATA ) >
<!ATTLIST event name ( delay | keyClick | keyPress | keyRelease | mouseClick | mouseMove | mousePress | mouseRelease | mouseWheel ) #REQUIRED >

<!ELEMENT singleCheck ( ScreenCapture+ ) >

=== yulinliu/JQuickMacro/script/default._bak.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE Threads SYSTEM ".\JQuickMacro.dtd">
<Threads singleWindow="false" eventDelay="200" startWait="3000">
	<singleCheck>
		<ScreenCapture height="7" width="7" x="7" y="7">.\screen\1264132737731.png</ScreenCapture>
	</singleCheck>
	<Thread autodelay="10 * 60 * 1000" name="鎖定砥礪獅" repeatedly="true">
		<event name="mouseMove">50% , 50%</event>
		<event name="keyClick">VK_ESCAPE</event>
		<event name="mouseClick">BUTTON1_MASK</event>
		<event name="delay">500</event>
	</Thread>
	<Thread autodelay="7500" name="金錢鏢" repeatedly="true">
		<event name="keyClick">VK_F2</event>
		<event name="delay">1000</event>
	</Thread>
	<Thread autodelay="2 * 60 * 1000" name="絕招蠱" repeatedly="true">
		<event name="keyClick">VK_F3</event>
		<event name="delay">1000</event>
	</Thread>
	<ExitTime>-1</ExitTime>
</Threads>
